behaviors:
  PlayerMove:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 100000
      learning_rate: 1.0e-4
      beta: 2.0e-3
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    time_horizon: 64
    keep_checkpoints: 10
