behaviors:
  PlayerMove:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 3.0e-4
      batch_size: 64
      buffer_size: 10240
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
